"""Delete the image tables, and updated one image table

Revision ID: 3433bc4813f1
Revises: b457d3c6906c
Create Date: 2025-05-18 13:32:13.845546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3433bc4813f1'
down_revision: Union[str, None] = 'b457d3c6906c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_msds_images', table_name='msds_images')
    op.drop_table('msds_images')
    op.drop_index('idx_brand_logo_images', table_name='brand_logo_images')
    op.drop_table('brand_logo_images')
    op.drop_index('idx_alt_images', table_name='alt_images')
    op.drop_table('alt_images')
    op.add_column('product_images', sa.Column('main_image', sa.String(), nullable=True))
    op.add_column('product_images', sa.Column('alt_image', sa.String(), nullable=True))
    op.add_column('product_images', sa.Column('alt_image_variant1', sa.String(), nullable=True))
    op.add_column('product_images', sa.Column('alt_image_variant2', sa.String(), nullable=True))
    op.add_column('product_images', sa.Column('alt_image_variant3', sa.String(), nullable=True))
    op.add_column('product_images', sa.Column('brand_logo_image', sa.String(), nullable=True))
    op.add_column('product_images', sa.Column('brand_logo_image_url', sa.String(), nullable=True))
    op.add_column('product_images', sa.Column('msds_image', sa.String(), nullable=True))
    op.add_column('product_images', sa.Column('msds_image_url', sa.String(), nullable=True))
    op.drop_index('idx_product_images', table_name='product_images')
    op.drop_column('product_images', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_images', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('idx_product_images', 'product_images', ['product_id'], unique=False)
    op.drop_column('product_images', 'msds_image_url')
    op.drop_column('product_images', 'msds_image')
    op.drop_column('product_images', 'brand_logo_image_url')
    op.drop_column('product_images', 'brand_logo_image')
    op.drop_column('product_images', 'alt_image_variant3')
    op.drop_column('product_images', 'alt_image_variant2')
    op.drop_column('product_images', 'alt_image_variant1')
    op.drop_column('product_images', 'alt_image')
    op.drop_column('product_images', 'main_image')
    op.create_table('alt_images',
    sa.Column('product_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('alt_image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('alt_image_variant1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('alt_image_variant2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('alt_image_variant3', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], name='alt_images_product_id_fkey')
    )
    op.create_index('idx_alt_images', 'alt_images', ['product_id'], unique=False)
    op.create_table('brand_logo_images',
    sa.Column('product_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('brand_logo_image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('brand_logo_image_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], name='brand_logo_images_product_id_fkey'),
    sa.PrimaryKeyConstraint('product_id', name='brand_logo_images_pkey')
    )
    op.create_index('idx_brand_logo_images', 'brand_logo_images', ['product_id'], unique=False)
    op.create_table('msds_images',
    sa.Column('product_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('msds_image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('msds_image_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], name='msds_images_product_id_fkey')
    )
    op.create_index('idx_msds_images', 'msds_images', ['product_id'], unique=False)
    # ### end Alembic commands ###
