"""UPDATED PRIMARY KEY

Revision ID: 580859621e86
Revises: 
Create Date: 2025-05-14 01:59:23.511755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '580859621e86'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('item_number', sa.String(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('stock_qty', sa.Integer(), nullable=True),
    sa.Column('item_weight', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_products_product_name'), 'products', ['product_name'], unique=False)
    op.create_index('ix_supplier_product_id', 'products', ['supplier_id', 'product_id'], unique=True)
    op.create_table('product_images',
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('image_variant1', sa.String(), nullable=True),
    sa.Column('image_variant2', sa.String(), nullable=True),
    sa.Column('image_variant3', sa.String(), nullable=True),
    sa.Column('image_variant4', sa.String(), nullable=True),
    sa.Column('image_variant5', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id', 'product_id'], ['products.supplier_id', 'products.product_id'], ),
    sa.PrimaryKeyConstraint('supplier_id', 'product_id')
    )
    op.create_index('idx_product_images', 'product_images', ['supplier_id', 'product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_product_images', table_name='product_images')
    op.drop_table('product_images')
    op.drop_index('ix_supplier_product_id', table_name='products')
    op.drop_index(op.f('ix_products_product_name'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
