"""Fix is_active column type

Revision ID: 8a2c9ffccae2
Revises: 47cee334c09a
Create Date: 2025-04-20 22:05:55.314488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a2c9ffccae2'
down_revision: Union[str, None] = '47cee334c09a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # Convert the column manually
    op.execute("""
        ALTER TABLE users
        ALTER COLUMN is_active
        TYPE BOOLEAN
        USING is_active::BOOLEAN
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
