"""Create products table

Revision ID: 930f355f43bf
Revises: b1f4458200f5
Create Date: 2025-04-30 15:03:39.956137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '930f355f43bf'
down_revision: Union[str, None] = 'b1f4458200f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_number', sa.String(), nullable=True),
    sa.Column('your_part_number', sa.String(), nullable=True),
    sa.Column('item_description', sa.String(), nullable=True),
    sa.Column('brand_name', sa.String(), nullable=True),
    sa.Column('vendor_part_number', sa.String(), nullable=True),
    sa.Column('vendor_name', sa.String(), nullable=True),
    sa.Column('product_category', sa.String(), nullable=True),
    sa.Column('product_subcategory', sa.String(), nullable=True),
    sa.Column('upc_code', sa.String(), nullable=True),
    sa.Column('min_order_qty', sa.Integer(), nullable=True),
    sa.Column('min_order_uom', sa.String(), nullable=True),
    sa.Column('uom_conversion', sa.String(), nullable=True),
    sa.Column('cost_uom', sa.String(), nullable=True),
    sa.Column('std_pkg_list_price', sa.Float(), nullable=True),
    sa.Column('std_pkg_cust_cost', sa.Float(), nullable=True),
    sa.Column('price_date', sa.Date(), nullable=True),
    sa.Column('item_weight', sa.Float(), nullable=True),
    sa.Column('item_height', sa.Float(), nullable=True),
    sa.Column('item_width', sa.Float(), nullable=True),
    sa.Column('item_length', sa.Float(), nullable=True),
    sa.Column('item_cube', sa.Float(), nullable=True),
    sa.Column('country_of_origin', sa.String(), nullable=True),
    sa.Column('hazmat_item', sa.Boolean(), nullable=True),
    sa.Column('special_order_item', sa.Boolean(), nullable=True),
    sa.Column('state_restricted', sa.Boolean(), nullable=True),
    sa.Column('recno', sa.Integer(), nullable=True),
    sa.Column('temp_price', sa.Float(), nullable=True),
    sa.Column('promo_price', sa.Float(), nullable=True),
    sa.Column('promo_start_date', sa.Date(), nullable=True),
    sa.Column('promo_end_date', sa.Date(), nullable=True),
    sa.Column('kf', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
