"""updated product table

Revision ID: cb14fb2c3c3f
Revises: 9a04c63dac2b
Create Date: 2025-05-18 18:00:28.509967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb14fb2c3c3f'
down_revision: Union[str, None] = '9a04c63dac2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('item_number', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'products', ['item_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_column('products', 'item_number')
    # ### end Alembic commands ###
