"""Delete the item number column

Revision ID: d07faf53b623
Revises: 3433bc4813f1
Create Date: 2025-05-18 16:50:45.877136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd07faf53b623'
down_revision: Union[str, None] = '3433bc4813f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'item_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('item_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
