"""UPDATED MODELS

Revision ID: f472a25a7c01
Revises: d96da4ee26f7
Create Date: 2025-05-17 18:16:14.875205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f472a25a7c01'
down_revision: Union[str, None] = 'd96da4ee26f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_alt_images', table_name='alt_images')
    op.create_index('idx_alt_images', 'alt_images', ['product_id'], unique=False)
    op.drop_constraint('alt_images_supplier_id_product_id_fkey', 'alt_images', type_='foreignkey')
    op.create_foreign_key(None, 'alt_images', 'products', ['product_id'], ['product_id'])
    op.drop_column('alt_images', 'supplier_id')
    op.drop_index('idx_brand_logo_images', table_name='brand_logo_images')
    op.create_index('idx_brand_logo_images', 'brand_logo_images', ['product_id'], unique=False)
    op.drop_constraint('brand_logo_images_supplier_id_product_id_fkey', 'brand_logo_images', type_='foreignkey')
    op.create_foreign_key(None, 'brand_logo_images', 'products', ['product_id'], ['product_id'])
    op.drop_column('brand_logo_images', 'supplier_id')
    op.drop_index('idx_msds_images', table_name='msds_images')
    op.create_index('idx_msds_images', 'msds_images', ['product_id'], unique=False)
    op.drop_constraint('msds_images_supplier_id_product_id_fkey', 'msds_images', type_='foreignkey')
    op.create_foreign_key(None, 'msds_images', 'products', ['product_id'], ['product_id'])
    op.drop_column('msds_images', 'supplier_id')
    op.drop_index('idx_product_images', table_name='product_images')
    op.create_index('idx_product_images', 'product_images', ['product_id'], unique=False)
    op.drop_constraint('product_images_supplier_id_product_id_fkey', 'product_images', type_='foreignkey')
    op.create_foreign_key(None, 'product_images', 'products', ['product_id'], ['product_id'])
    op.drop_column('product_images', 'supplier_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_images', sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'product_images', type_='foreignkey')
    op.create_foreign_key('product_images_supplier_id_product_id_fkey', 'product_images', 'products', ['supplier_id', 'product_id'], ['supplier_id', 'product_id'])
    op.drop_index('idx_product_images', table_name='product_images')
    op.create_index('idx_product_images', 'product_images', ['supplier_id', 'product_id'], unique=False)
    op.add_column('msds_images', sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'msds_images', type_='foreignkey')
    op.create_foreign_key('msds_images_supplier_id_product_id_fkey', 'msds_images', 'products', ['supplier_id', 'product_id'], ['supplier_id', 'product_id'])
    op.drop_index('idx_msds_images', table_name='msds_images')
    op.create_index('idx_msds_images', 'msds_images', ['supplier_id', 'product_id'], unique=False)
    op.add_column('brand_logo_images', sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'brand_logo_images', type_='foreignkey')
    op.create_foreign_key('brand_logo_images_supplier_id_product_id_fkey', 'brand_logo_images', 'products', ['supplier_id', 'product_id'], ['supplier_id', 'product_id'])
    op.drop_index('idx_brand_logo_images', table_name='brand_logo_images')
    op.create_index('idx_brand_logo_images', 'brand_logo_images', ['supplier_id', 'product_id'], unique=False)
    op.add_column('alt_images', sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'alt_images', type_='foreignkey')
    op.create_foreign_key('alt_images_supplier_id_product_id_fkey', 'alt_images', 'products', ['supplier_id', 'product_id'], ['supplier_id', 'product_id'])
    op.drop_index('idx_alt_images', table_name='alt_images')
    op.create_index('idx_alt_images', 'alt_images', ['supplier_id', 'product_id'], unique=False)
    # ### end Alembic commands ###
